version: "3.4"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 8000:8000
    volumes:
      - ./src:/api/src
    image: board/api
    command: sh -c "npm start"
